server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dashaun/dev.dashaun.config
          tryMasterBranch: false
          defaultLabel: main
        health:
          enabled: false
